#!/usr/bin/env bash

# Run larnyx --update to update Docker image

args=()
tag='latest'
docker='docker'
port='5002'

while [[ -n "$1" ]]; do
    if [[ "$1" == '--update' ]]; then
        # Update Docker image
        update='1'
    elif [[ "$1" == '--port' ]]; then
        port="$2"
        args+=('--port' "${port}")
        shift 1
    else
        args+=("$1")
    fi

    shift 1
done

if [[ -n "${update}" ]]; then
    docker pull "rhasspy/larynx:${tag}"
fi

docker_run_args=()

if [[ -d /etc/ssl/certs ]]; then
    # Map SSL certs path for downloading voices
    docker_run_args+=('-v' '/etc/ssl/certs:/etc/ssl/certs')
fi


"${docker}" run \
            -it \
            -p "${port}:${port}" \
            -e "HOME=${HOME}" \
            -v "$HOME:${HOME}" \
            -w "${PWD}" \
            --user "$(id -u):$(id -g)" "${docker_run_args[@]}" \
            "rhasspy/larynx:${tag}" \
            "${args[@]}"
