#!/usr/bin/env bash

# Run larnyx --update to update Docker image

args=()
tag='latest'
docker='docker'

while [[ -n "$1" ]]; do
    if [[ "$1" == '--update' ]]; then
        # Update Docker image
        update='1'
    else
        args+=("$1")
    fi

    shift 1
done

if [[ -n "${update}" ]]; then
    docker pull "rhasspy/larynx:${tag}"
fi

docker_run_args=()

if [[ -d /usr/share/ca-certificates ]]; then
    # Map SSL certs path for downloading voices
    docker_run_args+=('-v' '/usr/share/ca-certificates:/usr/share/ca-certificates')
fi

if [[ -d /etc/ssl/certs ]]; then
    # This directory seems to usually have symlinks to /usr/share/ca-certificates
    docker_run_args+=('-v' '/etc/ssl/certs:/etc/ssl/certs')
fi

"${docker}" run \
            -i \
            -e "HOME=${HOME}" \
            -v "$HOME:${HOME}" \
            -w "${PWD}" \
            --device /dev/snd:/dev/snd \
            --user "$(id -u):$(id -g)" "${docker_run_args[@]}" \
            --entrypoint '/home/larynx/app/.venv/bin/python3' \
            "rhasspy/larynx:${tag}" \
            -m larynx \
            "${args[@]}"
