#!/usr/bin/env bash

# Run larnyx --update to update Docker image

args=()
tag='latest'
docker='docker'
port='5002'

while [[ -n "$1" ]]; do
    if [[ "$1" == '--update' ]]; then
        # Update Docker image
        update='1'
    elif [[ "$1" == '--port' ]]; then
        port="$2"
        args+=("$1")
    else
        args+=("$1")
    fi

    shift 1
done

if [[ -n "${update}" ]]; then
    docker pull "rhasspy/larynx:${tag}"
fi

"${docker}" run \
            -it \
            -p "${port}:${port}" \
            -e "HOME=${HOME}" \
            -v "$HOME:${HOME}" \
            -w "${PWD}" \
            --user "$(id -u):$(id -g)" \
            "rhasspy/larynx:${tag}" \
            "${args[@]}"
